name: firebase_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  firebase_storage: ^13.0.3
  cloud_firestore: ^6.0.3
  firebase_messaging: ^16.0.3
  firebase_app_check: ^0.4.1+1
  google_sign_in: ^6.2.2
  get: ^4.6.6
  connectivity_plus: ^6.0.5
  google_fonts: ^6.2.1
  device_preview: ^1.0.0
  loading_animation_widget: ^1.3.0
  image_picker: ^1.0.7
  dartz: ^0.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/noty_icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
